import '../globals.css'
import '../styles/theme.css'
import 'remixicon/fonts/remixicon.css'
import LeftSidebar from '@/components/LeftSidebar'
import Header from '@/components/Header'

//  TODO: right side bar with social media links and color switch button, left side bar with title and some nav elements. main page 100  vh with some animations and some stuff then scroll down to blog posts
export const metadata = {
  title: 'Stratified',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
          <div className='mainCont'>
            <Header/>
            <div>
              <LeftSidebar />
              {children}
            </div>

          </div>
        </body>
    </html>
  )
}
